import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  TouchableOpacity,
  ScrollView,
  Image,
  Alert,
  Share,
} from 'react-native';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Copy, Check, Download, Share2, QrCode } from 'lucide-react-native';
import * as FileSystem from 'expo-file-system';
import * as MediaLibrary from 'expo-media-library';
import { useToast } from '../components/ToastProvider';
// Using base64 QR code from server instead of generating client-side

export default function UploadSuccessScreen() {
  const params = useLocalSearchParams();
  const router = useRouter();
  const shortUrl = (params.shortUrl as string) || '';
  const qrCode = (params.qrCode as string) || '';
  const uploadId = (params.uploadId as string) || '';
  const showToast = useToast();

  const [copied, setCopied] = useState(false);
  const [qrCodeSvg, setQrCodeSvg] = useState<string | null>(null);

  // Generate QR code if not provided
  useEffect(() => {
    if (!qrCode && shortUrl) {
      // QR code will be generated by the component
      setQrCodeSvg(shortUrl);
    } else if (qrCode) {
      setQrCodeSvg(qrCode);
    }
  }, [shortUrl, qrCode]);

  // Copy link to clipboard
  const handleCopyLink = async () => {
    if (!shortUrl) return;
    
    try {
      // Using expo-clipboard would be better, but using basic approach
      await Share.share({
        message: shortUrl,
      });
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      Alert.alert('Error', 'Failed to copy link');
    }
  };

  // Share link
  const handleShare = async () => {
    if (!shortUrl) return;

    try {
      const result = await Share.share({
        message: `Check out this content: ${shortUrl}`,
        url: shortUrl,
      });

      if (result.action === Share.sharedAction) {
        showToast('Link shared successfully.');
      }
    } catch (error) {
      Alert.alert('Error', 'Failed to share link');
    }
  };

  const handlePlayInApp = () => {
    if (!shortUrl) return;
    router.push({
      pathname: '/videoplay/VideoPlayerPage',
      params: { shortUrl: encodeURIComponent(shortUrl), title: 'Teleplay Content' },
    });
  };

  // Download QR code
  const handleDownloadQR = async () => {
    if (!qrCodeSvg) return;

    try {
      const { status } = await MediaLibrary.requestPermissionsAsync();
      if (status !== 'granted') {
        Alert.alert('Permission Required', 'Please grant storage permission to download QR code');
        return;
      }

      // For base64 QR codes from server
      if (qrCode.startsWith('data:image')) {
        const base64Data = qrCode.split(',')[1];
        const fileUri = `${FileSystem.documentDirectory}qr-${Date.now()}.png`;
        
        await FileSystem.writeAsStringAsync(fileUri, base64Data, {
          encoding: FileSystem.EncodingType.Base64,
        });

        const asset = await MediaLibrary.createAssetAsync(fileUri);
        await MediaLibrary.createAlbumAsync('Teleplay', asset, false);
        
        showToast('QR code saved to gallery.');
      } else {
        showToast('QR code download is coming soon.', 'info');
      }
    } catch (error) {
      console.error('Error downloading QR code:', error);
      Alert.alert('Error', 'Failed to download QR code');
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <Stack.Screen
        options={{
          title: 'Upload Successful',
          headerShown: true,
        }}
      />
      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        {/* Success Message */}
        <View style={styles.successHeader}>
          <Text style={styles.successTitle}>Upload Successful!</Text>
          <Text style={styles.successSubtitle}>Your content is now live</Text>
        </View>

        {shortUrl && (
          <>
            {/* Short Link Section */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Shortened Link</Text>
              <View style={styles.linkContainer}>
                <Text style={styles.linkText} numberOfLines={2}>
                  {shortUrl}
                </Text>
                <TouchableOpacity
                  style={[styles.copyButton, copied && styles.copyButtonActive]}
                  onPress={handleCopyLink}
                >
                  {copied ? (
                    <>
                      <Check size={20} color="#fff" />
                      <Text style={styles.copyButtonText}>Copied!</Text>
                    </>
                  ) : (
                    <>
                      <Copy size={20} color="#fff" />
                      <Text style={styles.copyButtonText}>Copy</Text>
                    </>
                  )}
                </TouchableOpacity>
              </View>
            </View>

            {/* QR Code Section */}
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>QR Code</Text>
              <View style={styles.qrContainer}>
                {qrCode && qrCode.startsWith('data:image') ? (
                  <Image
                    source={{ uri: qrCode }}
                    style={styles.qrImage}
                    resizeMode="contain"
                  />
                ) : shortUrl ? (
                  <View style={styles.qrPlaceholder}>
                    <QrCode size={80} color="#ccc" />
                    <Text style={styles.qrPlaceholderText}>
                      Scan this code to access: {shortUrl}
                    </Text>
                  </View>
                ) : (
                  <View style={styles.qrPlaceholder}>
                    <QrCode size={80} color="#ccc" />
                    <Text style={styles.qrPlaceholderText}>No QR code available</Text>
                  </View>
                )}
              </View>
              
              <View style={styles.qrActions}>
                <TouchableOpacity
                  style={styles.actionButton}
                  onPress={handleDownloadQR}
                >
                  <Download size={20} color="#1a9bd7" />
                  <Text style={styles.actionButtonText}>Download</Text>
                </TouchableOpacity>
                
                <TouchableOpacity
                  style={styles.actionButton}
                  onPress={handleShare}
                >
                  <Share2 size={20} color="#1a9bd7" />
                  <Text style={styles.actionButtonText}>Share</Text>
                </TouchableOpacity>
              </View>
            </View>
          </>
        )}

        {/* Action Buttons */}
        <View style={styles.actions}>
          <TouchableOpacity style={styles.primaryButton} onPress={handlePlayInApp}>
            <Text style={styles.primaryButtonText}>Play in App</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.primaryButton, { marginTop: 12 }]}
            onPress={() => router.push('/(tabs)')}
          >
            <Text style={styles.primaryButtonText}>Back to Home</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  successHeader: {
    alignItems: 'center',
    marginBottom: 30,
    paddingVertical: 20,
  },
  successTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1a9bd7',
    marginBottom: 8,
  },
  successSubtitle: {
    fontSize: 16,
    color: '#666',
  },
  section: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 15,
  },
  linkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  linkText: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    padding: 12,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1a9bd7',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    gap: 8,
  },
  copyButtonActive: {
    backgroundColor: '#16a085',
  },
  copyButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  qrContainer: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#f9f9f9',
    borderRadius: 12,
    marginBottom: 15,
  },
  qrImage: {
    width: 200,
    height: 200,
  },
  qrPlaceholder: {
    alignItems: 'center',
    padding: 40,
  },
  qrPlaceholderText: {
    marginTop: 10,
    color: '#999',
    fontSize: 14,
  },
  qrActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 10,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    gap: 8,
    flex: 1,
    justifyContent: 'center',
  },
  actionButtonText: {
    color: '#1a9bd7',
    fontWeight: '600',
    fontSize: 14,
  },
  actions: {
    marginTop: 10,
  },
  primaryButton: {
    backgroundColor: '#1a9bd7',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
